Update cac 0.4.1

diff --git a/bark/cac b/bark/cac
--- a/bark/cac
+++ b/bark/cac
@@ -2,7 +2,7 @@
 
 
 readonly _command="${0##*/}"
-readonly _c_version='0.4.0-4'
+readonly _c_version='0.4.1'
 export LANG=en_US.UTF-8
 _start_time="$(date "+%Y-%m-%d-%H%M%S")"
 _path="$(echo "${1}" | sed 's#/$##')"
@@ -94,35 +94,39 @@ _get_app_info(){
 			t="$((t+1))"
 			echo "[${t}/${t_max}] now retry"
 		else
-			break
+			if jq "." "${_tmp_file}" >"${_cac_path}/${2}_${1}-new.js"; then
+				break
+			else
+				echo '[x] Failed to parse data, retry download...'
+				t="$((t+1))"
+				echo "[${t}/${t_max}] now retry"
+			fi
 		fi
 	done
-	unset t t_max
-	if jq "." "${_tmp_file}" >"${_cac_path}/${2}_${1}-new.js"; then
-		_bundle="$(jq -r ".data[].attributes.platformAttributes.ios.bundleId" "${_cac_path}/${2}_${1}-new.js")"
-		_version="$(jq -r ".data[].attributes.platformAttributes.ios.versionHistory[0].versionDisplay" "${_cac_path}/${2}_${1}-new.js")"
-		_version_id="$(jq -r ".data[].attributes.platformAttributes.ios.versionHistory[0].externalVersionId" "${_cac_path}/${2}_${1}-new.js")"
-		_version_release_timestamp="$(jq -r ".data[].attributes.platformAttributes.ios.versionHistory[0].releaseTimestamp" "${_cac_path}/${2}_${1}-new.js")"
-		_name="$(jq -r ".data[].attributes.name" "${_cac_path}/${2}_${1}-new.js")"
-		_image="$(jq -r ".data[].attributes.platformAttributes.ios.artwork.url" "${_cac_path}/${2}_${1}-new.js")"
-		_image="${_image%\/*}/100x100bb.jpg"
-		_price="$(jq -r ".data[].attributes.platformAttributes.ios.offers[0].currencyCode" "${_cac_path}/${2}_${1}-new.js") $(jq -r ".data[].attributes.platformAttributes.ios.offers[0].priceString" "${_cac_path}/${2}_${1}-new.js")"
-		_record="${_version},${_version_id}"
-		if [ -z "$(echo "${_price}" | tr -dc '1-9')" ]; then
-			unset _price
-		fi
-		if [ ! -f "${_record_path}/${2}_${1}.csv" ]; then
-			echo 'Version,id' >"${_record_path}/${2}_${1}.csv"
-		fi
-		if ! grep -q "${_record}" "${_record_path}/${2}_${1}.csv" 2>>/dev/null; then
-			echo "${_record}" >>"${_record_path}/${2}_${1}.csv"
-		fi
-		if jq -r ".data[].id" "${_cac_path}/${2}_${1}-new.js" | grep -q "^${2}$"; then
-			jo status='0' id="${2}" bundle="${_bundle}" name="${_name}" version="${_version}" version_id="${_version_id}" version_release_timestamp="${_version_release_timestamp}" price="${_price}" image="${_image}" | jq >"${_cac_path}/${2}_${1}-new.js"
-		else
-			jo status='1' id="${2}" | jq >"${_cac_path}/${2}_${1}-new.js"
-		fi
+	_bundle="$(jq -r ".data[].attributes.platformAttributes.ios.bundleId" "${_cac_path}/${2}_${1}-new.js")"
+	_version="$(jq -r ".data[].attributes.platformAttributes.ios.versionHistory[0].versionDisplay" "${_cac_path}/${2}_${1}-new.js")"
+	_version_id="$(jq -r ".data[].attributes.platformAttributes.ios.versionHistory[0].externalVersionId" "${_cac_path}/${2}_${1}-new.js")"
+	_version_release_timestamp="$(jq -r ".data[].attributes.platformAttributes.ios.versionHistory[0].releaseTimestamp" "${_cac_path}/${2}_${1}-new.js")"
+	_name="$(jq -r ".data[].attributes.name" "${_cac_path}/${2}_${1}-new.js")"
+	_image="$(jq -r ".data[].attributes.platformAttributes.ios.artwork.url" "${_cac_path}/${2}_${1}-new.js")"
+	_image="${_image%\/*}/100x100bb.jpg"
+	_price="$(jq -r ".data[].attributes.platformAttributes.ios.offers[0].currencyCode" "${_cac_path}/${2}_${1}-new.js") $(jq -r ".data[].attributes.platformAttributes.ios.offers[0].priceString" "${_cac_path}/${2}_${1}-new.js")"
+	_record="${_version},${_version_id}"
+	if [ -z "$(echo "${_price}" | tr -dc '1-9')" ]; then
+		unset _price
 	fi
+	if [ ! -f "${_record_path}/${2}_${1}.csv" ]; then
+		echo 'Version,id' >"${_record_path}/${2}_${1}.csv"
+	fi
+	if ! grep -q "${_record}" "${_record_path}/${2}_${1}.csv" 2>>/dev/null; then
+		echo "${_record}" >>"${_record_path}/${2}_${1}.csv"
+	fi
+	if jq -r ".data[].id" "${_cac_path}/${2}_${1}-new.js" | grep -q "^${2}$"; then
+		jo status='0' id="${2}" bundle="${_bundle}" name="${_name}" version="${_version}" version_id="${_version_id}" version_release_timestamp="${_version_release_timestamp}" price="${_price}" image="${_image}" | jq >"${_cac_path}/${2}_${1}-new.js"
+	else
+		jo status='1' id="${2}" | jq >"${_cac_path}/${2}_${1}-new.js"
+	fi
+	unset t t_max
 	rm -f "${_tmp_file}"
 }
 
