Update cac 0.3.7

diff --git a/bark/cac b/bark/cac
--- a/bark/cac
+++ b/bark/cac
@@ -2,7 +2,7 @@
 
 
 readonly _command="${0##*/}"
-readonly _c_version='0.3.6-2'
+readonly _c_version='0.3.7'
 export LANG=en_US.UTF-8
 _start_time="$(date "+%Y-%m-%d-%H%M%S")"
 _path="$(echo "${1}" | sed 's#/$##')"
@@ -10,8 +10,16 @@ _cac_path="${_path}/Caches/com.nan.cac"
 _record_path="${_path}/Record/com.nan.cac"
 mkdir -p "${_cac_path}" "${_record_path}"
 readonly _config="$(jq "." "${_path}/Preferences/com.nan.cac.js")"
-_authorization='Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlU4UlRZVjVaRFMifQ.eyJpc3MiOiI3TktaMlZQNDhaIiwiaWF0IjoxNzcwODcxMzg5LCJleHAiOjE3NzgxMjg5ODksInJvb3RfaHR0cHNfb3JpZ2luIjpbImFwcGxlLmNvbSJdfQ.Tewb7DQbQYYjwlyHRehBb7Ksjcrd6wtg1xIfazeUE5iLQNPWGgh650cGJBeDjRhzk7fKIp-QyPigT14bV98Epw'
 echo "version: ${_c_version}"
+
+_token="$(curl -s 'https://invalidunit.github.io/token/asw')"
+if printf '%s\n' "${_token}" | jq -r ".status" | grep -q '^0$'; then
+	_authorization="Bearer $(printf '%s\n' "${_token}" | jq -r ".token")"
+	unset _token
+else
+	echo '[x] Failed to obtain token'
+	exit 1
+fi
 
 if [ -d '/proc/' ]; then
 	#openwrt not have ps -p
